### ISSUE TITLE
结构标签的使用及 class 命名

### ISSUE THREAD

**Issue by zhuayu** [xiaojilinggui/Baidu#3]
`<div class="header"></div>`

`<div class="footer"></div>`

`<div class="head-nav">`

可以使用结构标签 `<header></header>`,`<footer></footer>`,`<nav></nav>`

另外 class 命名可以参照事例子。在此次中，`class="nav"`使用不规范，应该为 `class="nav-item"` 更合适。

**Comment by xiaojilinggui** [comment]
已更改

**Comment by zhuayu** [comment]
一些命名还是不够规范，body 下一级的标签建议加一个 page- 前缀。参考[百度 HTML DEMO](https://aitschool.github.io/html/06_task.html)

**Comment by xiaojilinggui** [comment]
已更改
