### ISSUE TITLE
盒模型

### ISSUE THREAD

**Issue by Amcent** [xiaojilinggui/Baidu#7]
<div class="qrcode-contaienr">
  <img class="qrcode" src="xxxx">
</div>
<p class="qrcode-text">百度</p>

这里最好不要这样写，按照你的语义来写的话'qrcode-text'标签应该是属于'qrcode-container'里，而不是单独在外，可以给他们再套一个大的container或者把p放进container里，再另给<img>加一层div

**Comment by xiaojilinggui** [comment]
已更改
