### ISSUE TITLE
css书写顺序

### ISSUE THREAD

**Issue by Amcent** [xiaojilinggui/Baidu#8]
css的书写顺序应该有一套特定的规范，以便于阅读和维护：
1. Positioning (position, top, right, z-index, display, float等)
2. Box model (width, height, padding, margin等)
3. Typographic(font, line-height, letter-spacing, color- text-align等)
4. Visual(background, border等)
5. Other (animation, transition等)

**Comment by xiaojilinggui** [comment]
已修改
